#!/usr/bin/env bash
# This script kills all running instances of the 4-to_infinity_and_beyond script

# Find the PID(s) of the running script and kill them
kill "$(pgrep -f 4-to_infinity_and_beyond)"
