#!/usr/bin/env bash
# Define a trap for SIGTERM that prints the message but does not exit
trap 'echo "I am invincible!!!"' TERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
