#!/usr/bin/env bash
# Script that handles SIGTERM and loops indefinitely

# Trap SIGTERM and print the required message
trap "echo 'I am invincible!!!'" SIGTERM

# Infinite loop with 2-second sleep
while true
do
    echo "To infinity and beyond"
    sleep 2
done
